services:
  spark:
    image: lha151105/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONPATH=/tmp/python_packages
    ports:
      - '8080:8080'
      - '7077:7077'
      - '6066:6066'
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
    command: sh -c "pip install --target /tmp/python_packages numpy && tail -f /dev/null"
  spark-worker:
    image: lha151105/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONPATH=/tmp/python_packages
    ports:
      - '28081:8081'
      - '24040:4040'
      - '24041:4041'
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
    command: sh -c "pip install --target /tmp/python_packages numpy && tail -f /dev/null"
  data-source:
    image: lha151105/python:latest
    environment:
      - TOKEN=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
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
    ports:
      - "9999:9999"
    command: python3.9 -u /streaming/data_source.py
  webapp:
    image: lha151105/python:latest
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
    ports:
      - '5000:5000'
    command: bash -c "pip3.9 install flask redis matplotlib && cd /streaming/webapp && python3.9 web_app.py"
  redis:
    image: lha151105/redis:latest
    ports:
      - '6379:6379'
